### ISSUE TITLE
Getting 500 upon adding the extension to list of plugins

### ISSUE THREAD

**Issue by tgirgin23** [ViderumGlobal/ckanext-requestdata#22]
I have been trying to install the extension today without any success. I have followed the installation process of CKAN [http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html](url) and using [https://github.com/ViderumGlobal/ckanext-requestdata#development-installation](url) as the installation process for ckanext-requestdata.

Is it an absolute necessity to use a CKAN virtualenv if CKAN was installed using the Ubuntu package manager?

Currently, I am getting a 500 error when trying to connect to my installation of CKAN on Ubuntu 14.04. Any idea what could be causing the issue?

Here is my CKAN log file:

> mod_wsgi (pid=7222): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=7222): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
Traceback (most recent call last):
  File "/etc/ckan/default/apache.wsgi", line 9, in <module>
     fileConfig(config_filepath)
   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/util/logging_config.py", line 100, in fileConfig
     handlers = _install_handlers(cp, formatters)
   File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/util/logging_config.py", line 173, in _install_handlers
    h = klass(*args)
TypeError: __init__() takes at most 2 arguments (5 given)
mod_wsgi (pid=7223): Target WSGI script '/etc/ckan/default/apache.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=7223): Exception occurred processing WSGI script '/etc/ckan/default/apache.wsgi'.
Traceback (most recent call last):
  File "/etc/ckan/default/apache.wsgi", line 9, in <module>
    fileConfig(config_filepath)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/util/logging_config.py", line 100, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/ckan/default/lib/python2.7/site-packages/paste/script/util/logging_config.py", line 173, in _install_handlers
    h = klass(*args)
TypeError: __init__() takes at most 2 arguments (5 given)

Thank you!

**Comment by ZoranPandovski** [comment]
Hi @tgirgin23 did you resolve the issue?
